CREATE TABLE MB_CUENTA_BANCARIA (
  cuenta_id NUMBER(10) NOT NULL,
  empresa_id NUMBER(10) NOT NULL,
  banco_id NUMBER(10) NOT NULL,
  moneda_id NUMBER(5) NOT NULL,
  tipo_cuenta_id NUMBER(10) NOT NULL,
  responsable_id NUMBER(10) NOT NULL,
  codigo_cuenta VARCHAR2(20) NOT NULL,
  numero_cuenta VARCHAR2(20) NOT NULL,
  nombre_interno VARCHAR2(80) NOT NULL,
  saldo_inicial NUMBER(18,2) NOT NULL,
  fecha_apertura DATE NOT NULL,
  uso_principal VARCHAR2(15) NOT NULL,
  permite_cobros CHAR(1) NOT NULL,
  permite_pagos CHAR(1) NOT NULL,
  permite_cheques CHAR(1) NOT NULL,
  permite_transferencias CHAR(1) NOT NULL,
  fecha_cierre DATE,
  estado VARCHAR2(15) NOT NULL,
  observaciones VARCHAR2(500),
  creado_por NUMBER(10) NOT NULL,
  creado_en TIMESTAMP NOT NULL,
  modificado_por NUMBER(10),
  modificado_en TIMESTAMP,
  CONSTRAINT mb_pk_cuenta_bancaria PRIMARY KEY (cuenta_id),
  CONSTRAINT mb_fk_cuenta_banco FOREIGN KEY (banco_id) REFERENCES MB_BANCO(banco_id),
  CONSTRAINT mb_fk_cuenta_tipo FOREIGN KEY (tipo_cuenta_id) REFERENCES MB_CATALOGO_BANCARIO(catalogo_id),
  CONSTRAINT mb_uq_cuenta_codigo UNIQUE (codigo_cuenta),
  CONSTRAINT mb_uq_cuenta_numero UNIQUE (empresa_id,banco_id,numero_cuenta),
  CONSTRAINT mb_ck_cuenta_numero CHECK (REGEXP_LIKE(numero_cuenta,'^[0-9]{6,20}$')),
  CONSTRAINT mb_ck_cuenta_uso CHECK (uso_principal IN ('COBROS','PAGOS','AMBOS')),
  CONSTRAINT mb_ck_cuenta_flags CHECK (permite_cobros IN ('S','N') AND permite_pagos IN ('S','N') AND permite_cheques IN ('S','N') AND permite_transferencias IN ('S','N')),
  CONSTRAINT mb_ck_cuenta_estado CHECK (estado IN ('BORRADOR','ACTIVA','INACTIVA','CERRADA'))
);
