CREATE TABLE MB_CUENTA_BANCARIA_PROVEEDOR (
  cta_proveedor_id NUMBER(19) NOT NULL,
  proveedor_id NUMBER(10) NOT NULL,
  banco_id NUMBER(10) NOT NULL,
  tipo_cuenta_id NUMBER(10) NOT NULL,
  moneda_id NUMBER(5) NOT NULL,
  cuenta_anterior_id NUMBER(19),
  titular VARCHAR2(150) NOT NULL,
  numero_cuenta VARCHAR2(34) NOT NULL,
  carta_solicitud_doc_id NUMBER(19) NOT NULL,
  constancia_banco_doc_id NUMBER(19) NOT NULL,
  representante_doc_id NUMBER(19),
  motivo_registro VARCHAR2(500) NOT NULL,
  fecha_vigencia DATE,
  estado VARCHAR2(20) NOT NULL,
  observaciones VARCHAR2(500),
  solicitado_por NUMBER(10) NOT NULL,
  solicitado_en TIMESTAMP NOT NULL,
  CONSTRAINT mb_pk_cta_proveedor PRIMARY KEY (cta_proveedor_id),
  CONSTRAINT mb_fk_cp_banco FOREIGN KEY (banco_id) REFERENCES MB_BANCO(banco_id),
  CONSTRAINT mb_fk_cp_tipo FOREIGN KEY (tipo_cuenta_id) REFERENCES MB_CATALOGO_BANCARIO(catalogo_id),
  CONSTRAINT mb_fk_cp_anterior FOREIGN KEY (cuenta_anterior_id) REFERENCES MB_CUENTA_BANCARIA_PROVEEDOR(cta_proveedor_id),
  CONSTRAINT mb_fk_cp_carta FOREIGN KEY (carta_solicitud_doc_id) REFERENCES MB_DOCUMENTO_BANCARIO(documento_id),
  CONSTRAINT mb_fk_cp_constancia FOREIGN KEY (constancia_banco_doc_id) REFERENCES MB_DOCUMENTO_BANCARIO(documento_id),
  CONSTRAINT mb_fk_cp_repr FOREIGN KEY (representante_doc_id) REFERENCES MB_DOCUMENTO_BANCARIO(documento_id),
  CONSTRAINT mb_uq_cp_cuenta UNIQUE (proveedor_id,banco_id,numero_cuenta,moneda_id),
  CONSTRAINT mb_ck_cp_estado CHECK (estado IN ('PENDIENTE','EN_REVISION','VERIFICADA','RECHAZADA','BLOQUEADA','INACTIVA'))
);
