-- Persona 4 - DDL: MB_CHEQUERA
-- Extraído del esquema ERP_BANCOS exportado el 2026-09-11.
-- Contiene tabla, restricciones y claves foráneas propias del objeto.

CREATE TABLE "MB_CHEQUERA" ("CHEQUERA_ID" NUMBER(19,0), "CUENTA_ID" NUMBER(10,0), "SERIE" VARCHAR2(30), "NUMERO_INICIAL" NUMBER(12,0), "NUMERO_FINAL" NUMBER(12,0), "FECHA_RECEPCION" DATE, "CUSTODIO_ID" NUMBER(10,0), "UBICACION_FISICA" VARCHAR2(150), "DOCUMENTO_RECEPCION_ID" NUMBER(19,0), "ESTADO" VARCHAR2(15), "OBSERVACIONES" VARCHAR2(500)) ;

ALTER TABLE "MB_CHEQUERA" MODIFY ("CHEQUERA_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" MODIFY ("CUENTA_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" MODIFY ("NUMERO_INICIAL" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" MODIFY ("NUMERO_FINAL" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" MODIFY ("FECHA_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" MODIFY ("CUSTODIO_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "MB_CHEQUERA" ADD CONSTRAINT "MB_CK_CHQRA_RANGO" CHECK (numero_inicial <= numero_final) ENABLE;
  ALTER TABLE "MB_CHEQUERA" ADD CONSTRAINT "MB_CK_CHQRA_ESTADO" CHECK (estado IN ('BORRADOR','ACTIVA','AGOTADA','INACTIVA')) ENABLE;
  ALTER TABLE "MB_CHEQUERA" ADD CONSTRAINT "MB_PK_CHEQUERA" PRIMARY KEY ("CHEQUERA_ID") USING INDEX  ENABLE;

ALTER TABLE "MB_CHEQUERA" ADD CONSTRAINT "MB_FK_CHQRA_CUENTA" FOREIGN KEY ("CUENTA_ID") REFERENCES "MB_CUENTA_BANCARIA" ("CUENTA_ID") ENABLE;
  ALTER TABLE "MB_CHEQUERA" ADD CONSTRAINT "MB_FK_CHQRA_DOC" FOREIGN KEY ("DOCUMENTO_RECEPCION_ID") REFERENCES "MB_DOCUMENTO_BANCARIO" ("DOCUMENTO_ID") ENABLE;
