-- Persona 4 - DDL: MB_PLANTILLA_CHEQUE
-- Extraído del esquema ERP_BANCOS exportado el 2026-09-11.
-- Contiene tabla, restricciones y claves foráneas propias del objeto.

CREATE TABLE "MB_PLANTILLA_CHEQUE" ("PLANTILLA_ID" NUMBER(19,0), "BANCO_ID" NUMBER(10,0), "TIPO_CUENTA_ID" NUMBER(10,0), "NOMBRE" VARCHAR2(100), "TAMANO_PAPEL" VARCHAR2(30), "ORIENTACION" VARCHAR2(15), "MARGEN_SUPERIOR_MM" NUMBER(8,2), "MARGEN_INFERIOR_MM" NUMBER(8,2), "MARGEN_IZQUIERDO_MM" NUMBER(8,2), "MARGEN_DERECHO_MM" NUMBER(8,2), "ARCHIVO_FONDO_ID" NUMBER(19,0), "ESTADO" VARCHAR2(15)) ;

ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("PLANTILLA_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("BANCO_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("TAMANO_PAPEL" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("ORIENTACION" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("MARGEN_SUPERIOR_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("MARGEN_INFERIOR_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("MARGEN_IZQUIERDO_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("MARGEN_DERECHO_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_CK_PCQ_ORIENT" CHECK (orientacion IN ('HORIZONTAL','VERTICAL')) ENABLE;
  ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_CK_PCQ_ESTADO" CHECK (estado IN ('ACTIVA','INACTIVA')) ENABLE;
  ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_PK_PLANTILLA_CHEQUE" PRIMARY KEY ("PLANTILLA_ID") USING INDEX  ENABLE;
  ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_UQ_PCQ" UNIQUE ("BANCO_ID", "NOMBRE") USING INDEX  ENABLE;

ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_FK_PCQ_BANCO" FOREIGN KEY ("BANCO_ID") REFERENCES "MB_BANCO" ("BANCO_ID") ENABLE;
  ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_FK_PCQ_TIPO" FOREIGN KEY ("TIPO_CUENTA_ID") REFERENCES "MB_CATALOGO_BANCARIO" ("CATALOGO_ID") ENABLE;
  ALTER TABLE "MB_PLANTILLA_CHEQUE" ADD CONSTRAINT "MB_FK_PCQ_FONDO" FOREIGN KEY ("ARCHIVO_FONDO_ID") REFERENCES "MB_DOCUMENTO_BANCARIO" ("DOCUMENTO_ID") ENABLE;
