-- Persona 4 - DDL: MB_PLANTILLA_CAMPO_CHEQUE
-- Extraído del esquema ERP_BANCOS exportado el 2026-09-11.
-- Contiene tabla, restricciones y claves foráneas propias del objeto.

CREATE TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ("CAMPO_PLANTILLA_ID" NUMBER(19,0), "PLANTILLA_ID" NUMBER(19,0), "CODIGO_CAMPO" VARCHAR2(30), "POSICION_X_MM" NUMBER(8,2), "POSICION_Y_MM" NUMBER(8,2), "ANCHO_MM" NUMBER(8,2), "ALTO_MM" NUMBER(8,2), "TAMANO_FUENTE" NUMBER(5,2), "ALINEACION" VARCHAR2(15), "ESTADO" VARCHAR2(15)) ;

ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("CAMPO_PLANTILLA_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("PLANTILLA_ID" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("CODIGO_CAMPO" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("POSICION_X_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("POSICION_Y_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("ANCHO_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("ALTO_MM" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("TAMANO_FUENTE" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("ALINEACION" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ADD CONSTRAINT "MB_CK_PCC_CODIGO" CHECK (codigo_campo IN ('FECHA','BENEFICIARIO','MONTO_NUM','MONTO_LETRAS','CONCEPTO')) ENABLE;
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ADD CONSTRAINT "MB_CK_PCC_ALINEA" CHECK (alineacion IN ('IZQUIERDA','CENTRO','DERECHA')) ENABLE;
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ADD CONSTRAINT "MB_CK_PCC_ESTADO" CHECK (estado IN ('ACTIVO','INACTIVO')) ENABLE;
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ADD CONSTRAINT "MB_PK_PLANTILLA_CAMPO" PRIMARY KEY ("CAMPO_PLANTILLA_ID") USING INDEX  ENABLE;
  ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ADD CONSTRAINT "MB_UQ_PCC" UNIQUE ("PLANTILLA_ID", "CODIGO_CAMPO") USING INDEX  ENABLE;

ALTER TABLE "MB_PLANTILLA_CAMPO_CHEQUE" ADD CONSTRAINT "MB_FK_PCC_PLANTILLA" FOREIGN KEY ("PLANTILLA_ID") REFERENCES "MB_PLANTILLA_CHEQUE" ("PLANTILLA_ID") ENABLE;
